/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyValue from './AnyValue';
import DBType from './DBType';

/**
 * The ConstantType model module.
 * @module model/ConstantType
 * @version 1.0.0
 */
class ConstantType {
    /**
     * Constructs a new <code>ConstantType</code>.
     * @alias module:model/ConstantType
     * @extends module:model/DBType
     * @implements module:model/DBType
     * @param objtp {String} 
     */
    constructor(objtp) { 
        DBType.initialize(this, objtp);
        ConstantType.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
    }

    /**
     * Constructs a <code>ConstantType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstantType} obj Optional instance to populate.
     * @return {module:model/ConstantType} The populated <code>ConstantType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstantType();
            DBType.constructFromObject(data, obj);
            DBType.constructFromObject(data, obj);

            if (data.hasOwnProperty('_constant')) {
                obj['_constant'] = AnyValue.constructFromObject(data['_constant']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AnyValue} _constant
 */
ConstantType.prototype['_constant'] = undefined;


// Implement DBType interface:
/**
 * @member {String} objtp
 * @default ''
 */
DBType.prototype['objtp'] = '';




export default ConstantType;

