/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PairRelKeyAnyValue from './PairRelKeyAnyValue';

/**
 * The DictElementRelKeyAnyValue model module.
 * @module model/DictElementRelKeyAnyValue
 * @version 1.0.0
 */
class DictElementRelKeyAnyValue {
    /**
     * Constructs a new <code>DictElementRelKeyAnyValue</code>.
     * @alias module:model/DictElementRelKeyAnyValue
     * @param objtp {module:model/DictElementRelKeyAnyValue.ObjtpEnum} 
     */
    constructor(objtp) { 
        
        DictElementRelKeyAnyValue.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>DictElementRelKeyAnyValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DictElementRelKeyAnyValue} obj Optional instance to populate.
     * @return {module:model/DictElementRelKeyAnyValue} The populated <code>DictElementRelKeyAnyValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DictElementRelKeyAnyValue();

            if (data.hasOwnProperty('dict_arr')) {
                obj['dict_arr'] = ApiClient.convertToType(data['dict_arr'], [PairRelKeyAnyValue]);
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PairRelKeyAnyValue>} dict_arr
 */
DictElementRelKeyAnyValue.prototype['dict_arr'] = undefined;

/**
 * @member {module:model/DictElementRelKeyAnyValue.ObjtpEnum} objtp
 * @default 'DictElement_RelKey_AnyValue'
 */
DictElementRelKeyAnyValue.prototype['objtp'] = 'DictElement_RelKey_AnyValue';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
DictElementRelKeyAnyValue['ObjtpEnum'] = {

    /**
     * value: "DictElement_RelKey_AnyValue"
     * @const
     */
    "DictElement_RelKey_AnyValue": "DictElement_RelKey_AnyValue"
};



export default DictElementRelKeyAnyValue;

