/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileSyntax model module.
 * @module model/FileSyntax
 * @version 1.0.0
 */
class FileSyntax {
    /**
     * Constructs a new <code>FileSyntax</code>.
     * @alias module:model/FileSyntax
     * @param objtp {String} 
     */
    constructor(objtp) { 
        
        FileSyntax.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>FileSyntax</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileSyntax} obj Optional instance to populate.
     * @return {module:model/FileSyntax} The populated <code>FileSyntax</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileSyntax();

            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} objtp
 * @default ''
 */
FileSyntax.prototype['objtp'] = '';






export default FileSyntax;

