/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelKey from './RelKey';

/**
 * The ICViolation model module.
 * @module model/ICViolation
 * @version 1.0.0
 */
class ICViolation {
    /**
     * Constructs a new <code>ICViolation</code>.
     * @alias module:model/ICViolation
     * @param relKey {module:model/RelKey} 
     * @param objtp {module:model/ICViolation.ObjtpEnum} 
     */
    constructor(relKey, objtp) { 
        
        ICViolation.initialize(this, relKey, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, relKey, objtp) { 
        obj['rel_key'] = relKey;
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>ICViolation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ICViolation} obj Optional instance to populate.
     * @return {module:model/ICViolation} The populated <code>ICViolation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ICViolation();

            if (data.hasOwnProperty('rel_key')) {
                obj['rel_key'] = RelKey.constructFromObject(data['rel_key']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RelKey} rel_key
 */
ICViolation.prototype['rel_key'] = undefined;

/**
 * @member {String} source
 * @default ''
 */
ICViolation.prototype['source'] = '';

/**
 * @member {module:model/ICViolation.ObjtpEnum} objtp
 * @default 'ICViolation'
 */
ICViolation.prototype['objtp'] = 'ICViolation';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
ICViolation['ObjtpEnum'] = {

    /**
     * value: "ICViolation"
     * @const
     */
    "ICViolation": "ICViolation"
};



export default ICViolation;

