/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyValue from './AnyValue';
import RelKey from './RelKey';

/**
 * The PairRelKeyAnyValue model module.
 * @module model/PairRelKeyAnyValue
 * @version 1.0.0
 */
class PairRelKeyAnyValue {
    /**
     * Constructs a new <code>PairRelKeyAnyValue</code>.
     * @alias module:model/PairRelKeyAnyValue
     * @param first {module:model/RelKey} 
     * @param objtp {module:model/PairRelKeyAnyValue.ObjtpEnum} 
     */
    constructor(first, objtp) { 
        
        PairRelKeyAnyValue.initialize(this, first, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, first, objtp) { 
        obj['first'] = first;
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>PairRelKeyAnyValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PairRelKeyAnyValue} obj Optional instance to populate.
     * @return {module:model/PairRelKeyAnyValue} The populated <code>PairRelKeyAnyValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PairRelKeyAnyValue();

            if (data.hasOwnProperty('first')) {
                obj['first'] = RelKey.constructFromObject(data['first']);
            }
            if (data.hasOwnProperty('second')) {
                obj['second'] = AnyValue.constructFromObject(data['second']);
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RelKey} first
 */
PairRelKeyAnyValue.prototype['first'] = undefined;

/**
 * @member {module:model/AnyValue} second
 */
PairRelKeyAnyValue.prototype['second'] = undefined;

/**
 * @member {module:model/PairRelKeyAnyValue.ObjtpEnum} objtp
 * @default 'Pair_RelKey_AnyValue'
 */
PairRelKeyAnyValue.prototype['objtp'] = 'Pair_RelKey_AnyValue';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
PairRelKeyAnyValue['ObjtpEnum'] = {

    /**
     * value: "Pair_RelKey_AnyValue"
     * @const
     */
    "Pair_RelKey_AnyValue": "Pair_RelKey_AnyValue"
};



export default PairRelKeyAnyValue;

