/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyValue from './AnyValue';

/**
 * The PairAnyValueAnyValue model module.
 * @module model/PairAnyValueAnyValue
 * @version 1.0.0
 */
class PairAnyValueAnyValue {
    /**
     * Constructs a new <code>PairAnyValueAnyValue</code>.
     * @alias module:model/PairAnyValueAnyValue
     * @param objtp {module:model/PairAnyValueAnyValue.ObjtpEnum} 
     */
    constructor(objtp) { 
        
        PairAnyValueAnyValue.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>PairAnyValueAnyValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PairAnyValueAnyValue} obj Optional instance to populate.
     * @return {module:model/PairAnyValueAnyValue} The populated <code>PairAnyValueAnyValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PairAnyValueAnyValue();

            if (data.hasOwnProperty('first')) {
                obj['first'] = AnyValue.constructFromObject(data['first']);
            }
            if (data.hasOwnProperty('second')) {
                obj['second'] = AnyValue.constructFromObject(data['second']);
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AnyValue} first
 */
PairAnyValueAnyValue.prototype['first'] = undefined;

/**
 * @member {module:model/AnyValue} second
 */
PairAnyValueAnyValue.prototype['second'] = undefined;

/**
 * @member {module:model/PairAnyValueAnyValue.ObjtpEnum} objtp
 * @default 'Pair_AnyValue_AnyValue'
 */
PairAnyValueAnyValue.prototype['objtp'] = 'Pair_AnyValue_AnyValue';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
PairAnyValueAnyValue['ObjtpEnum'] = {

    /**
     * value: "Pair_AnyValue_AnyValue"
     * @const
     */
    "Pair_AnyValue_AnyValue": "Pair_AnyValue_AnyValue"
};



export default PairAnyValueAnyValue;

