/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyValue from './AnyValue';
import Area from './Area';

/**
 * The Range model module.
 * @module model/Range
 * @version 1.0.0
 */
class Range {
    /**
     * Constructs a new <code>Range</code>.
     * @alias module:model/Range
     * @param area {module:model/Area} 
     * @param objtp {module:model/Range.ObjtpEnum} 
     */
    constructor(area, objtp) { 
        
        Range.initialize(this, area, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, area, objtp) { 
        obj['area'] = area;
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>Range</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Range} obj Optional instance to populate.
     * @return {module:model/Range} The populated <code>Range</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Range();

            if (data.hasOwnProperty('input')) {
                obj['input'] = AnyValue.constructFromObject(data['input']);
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = Area.constructFromObject(data['area']);
            }
            if (data.hasOwnProperty('start_byte')) {
                obj['start_byte'] = ApiClient.convertToType(data['start_byte'], 'Number');
            }
            if (data.hasOwnProperty('end_byte')) {
                obj['end_byte'] = ApiClient.convertToType(data['end_byte'], 'Number');
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AnyValue} input
 */
Range.prototype['input'] = undefined;

/**
 * @member {module:model/Area} area
 */
Range.prototype['area'] = undefined;

/**
 * @member {Number} start_byte
 */
Range.prototype['start_byte'] = undefined;

/**
 * @member {Number} end_byte
 */
Range.prototype['end_byte'] = undefined;

/**
 * @member {module:model/Range.ObjtpEnum} objtp
 * @default 'Range'
 */
Range.prototype['objtp'] = 'Range';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
Range['ObjtpEnum'] = {

    /**
     * value: "Range"
     * @const
     */
    "Range": "Range"
};



export default Range;

