/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DictElementRelKeyAnyValue from './DictElementRelKeyAnyValue';

/**
 * The RelDict model module.
 * @module model/RelDict
 * @version 1.0.0
 */
class RelDict {
    /**
     * Constructs a new <code>RelDict</code>.
     * @alias module:model/RelDict
     * @param objtp {module:model/RelDict.ObjtpEnum} 
     */
    constructor(objtp) { 
        
        RelDict.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>RelDict</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelDict} obj Optional instance to populate.
     * @return {module:model/RelDict} The populated <code>RelDict</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelDict();

            if (data.hasOwnProperty('dict_elem')) {
                obj['dict_elem'] = DictElementRelKeyAnyValue.constructFromObject(data['dict_elem']);
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DictElementRelKeyAnyValue} dict_elem
 */
RelDict.prototype['dict_elem'] = undefined;

/**
 * @member {module:model/RelDict.ObjtpEnum} objtp
 * @default 'RelDict'
 */
RelDict.prototype['objtp'] = 'RelDict';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
RelDict['ObjtpEnum'] = {

    /**
     * value: "RelDict"
     * @const
     */
    "RelDict": "RelDict"
};



export default RelDict;

