/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DBType from './DBType';

/**
 * The RelKey model module.
 * @module model/RelKey
 * @version 1.0.0
 */
class RelKey {
    /**
     * Constructs a new <code>RelKey</code>.
     * @alias module:model/RelKey
     * @param objtp {module:model/RelKey.ObjtpEnum} 
     */
    constructor(objtp) { 
        
        RelKey.initialize(this, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objtp) { 
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>RelKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelKey} obj Optional instance to populate.
     * @return {module:model/RelKey} The populated <code>RelKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelKey();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], [DBType]);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [DBType]);
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 * @default ''
 */
RelKey.prototype['name'] = '';

/**
 * @member {Array.<module:model/DBType>} keys
 */
RelKey.prototype['keys'] = undefined;

/**
 * @member {Array.<module:model/DBType>} values
 */
RelKey.prototype['values'] = undefined;

/**
 * @member {module:model/RelKey.ObjtpEnum} objtp
 * @default 'RelKey'
 */
RelKey.prototype['objtp'] = 'RelKey';





/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
RelKey['ObjtpEnum'] = {

    /**
     * value: "RelKey"
     * @const
     */
    "RelKey": "RelKey"
};



export default RelKey;

