/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LabeledAction from './LabeledAction';

/**
 * The Transaction model module.
 * @module model/Transaction
 * @version 1.0.0
 */
class Transaction {
    /**
     * Constructs a new <code>Transaction</code>.
     * @alias module:model/Transaction
     * @param mode {module:model/Transaction.ModeEnum} 
     * @param objtp {module:model/Transaction.ObjtpEnum} 
     */
    constructor(mode, objtp) { 
        
        Transaction.initialize(this, mode, objtp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mode, objtp) { 
        obj['mode'] = mode;
        obj['objtp'] = objtp;
    }

    /**
     * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Transaction} obj Optional instance to populate.
     * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Transaction();

            if (data.hasOwnProperty('dbname')) {
                obj['dbname'] = ApiClient.convertToType(data['dbname'], 'String');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
            if (data.hasOwnProperty('readonly')) {
                obj['readonly'] = ApiClient.convertToType(data['readonly'], 'Boolean');
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [LabeledAction]);
            }
            if (data.hasOwnProperty('abort')) {
                obj['abort'] = ApiClient.convertToType(data['abort'], 'Boolean');
            }
            if (data.hasOwnProperty('objtp')) {
                obj['objtp'] = ApiClient.convertToType(data['objtp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} dbname
 * @default ''
 */
Transaction.prototype['dbname'] = '';

/**
 * @member {module:model/Transaction.ModeEnum} mode
 * @default 'OPEN'
 */
Transaction.prototype['mode'] = 'OPEN';

/**
 * @member {Boolean} readonly
 * @default false
 */
Transaction.prototype['readonly'] = false;

/**
 * @member {Array.<module:model/LabeledAction>} actions
 */
Transaction.prototype['actions'] = undefined;

/**
 * @member {Boolean} abort
 * @default false
 */
Transaction.prototype['abort'] = false;

/**
 * @member {module:model/Transaction.ObjtpEnum} objtp
 * @default 'Transaction'
 */
Transaction.prototype['objtp'] = 'Transaction';





/**
 * Allowed values for the <code>mode</code> property.
 * @enum {String}
 * @readonly
 */
Transaction['ModeEnum'] = {

    /**
     * value: "OPEN"
     * @const
     */
    "OPEN": "OPEN",

    /**
     * value: "CREATE"
     * @const
     */
    "CREATE": "CREATE",

    /**
     * value: "CREATE_OVERWRITE"
     * @const
     */
    "CREATE_OVERWRITE": "CREATE_OVERWRITE",

    /**
     * value: "OPEN_OR_CREATE"
     * @const
     */
    "OPEN_OR_CREATE": "OPEN_OR_CREATE"
};


/**
 * Allowed values for the <code>objtp</code> property.
 * @enum {String}
 * @readonly
 */
Transaction['ObjtpEnum'] = {

    /**
     * value: "Transaction"
     * @const
     */
    "Transaction": "Transaction"
};



export default Transaction;

