/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DBType from './DBType';

/**
 * The WrappedType model module.
 * @module model/WrappedType
 * @version 1.0.0
 */
class WrappedType {
    /**
     * Constructs a new <code>WrappedType</code>.
     * @alias module:model/WrappedType
     * @extends module:model/DBType
     * @implements module:model/DBType
     * @param type {String} 
     */
    constructor(type) { 
        DBType.initialize(this, type);
        WrappedType.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
    }

    /**
     * Constructs a <code>WrappedType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WrappedType} obj Optional instance to populate.
     * @return {module:model/WrappedType} The populated <code>WrappedType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WrappedType();
            DBType.constructFromObject(data, obj);
            DBType.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement DBType interface:
/**
 * @member {String} type
 * @default ''
 */
DBType.prototype['type'] = '';




export default WrappedType;

