/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FrontProblem from './FrontProblem';
import Range from './Range';

/**
 * The InlineInconsistent model module.
 * @module model/InlineInconsistent
 * @version 1.1.3
 */
class InlineInconsistent {
    /**
     * Constructs a new <code>InlineInconsistent</code>.
     * @alias module:model/InlineInconsistent
     * @extends module:model/FrontProblem
     * @implements module:model/FrontProblem
     * @param type {String} 
     */
    constructor(type) { 
        FrontProblem.initialize(this, type);
        InlineInconsistent.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['name'] = name || '';
        obj['range'] = range;
    }

    /**
     * Constructs a <code>InlineInconsistent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineInconsistent} obj Optional instance to populate.
     * @return {module:model/InlineInconsistent} The populated <code>InlineInconsistent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineInconsistent();
            FrontProblem.constructFromObject(data, obj);
            FrontProblem.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = Range.constructFromObject(data['range']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 * @default ''
 */
InlineInconsistent.prototype['name'] = '';

/**
 * @member {module:model/Range} range
 */
InlineInconsistent.prototype['range'] = undefined;


// Implement FrontProblem interface:
/**
 * @member {String} type
 * @default ''
 */
FrontProblem.prototype['type'] = '';




export default InlineInconsistent;

