/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyType from './AnyType';
import FrontProblem from './FrontProblem';
import Range from './Range';

/**
 * The ShadowError model module.
 * @module model/ShadowError
 * @version 1.1.3
 */
class ShadowError {
    /**
     * Constructs a new <code>ShadowError</code>.
     * @alias module:model/ShadowError
     * @extends module:model/FrontProblem
     * @implements module:model/FrontProblem
     * @param type {String} 
     */
    constructor(type) { 
        FrontProblem.initialize(this, type);
        ShadowError.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['range'] = range;
        obj['var'] = _var || '';
    }

    /**
     * Constructs a <code>ShadowError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShadowError} obj Optional instance to populate.
     * @return {module:model/ShadowError} The populated <code>ShadowError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShadowError();
            FrontProblem.constructFromObject(data, obj);
            FrontProblem.constructFromObject(data, obj);

            if (data.hasOwnProperty('range')) {
                obj['range'] = Range.constructFromObject(data['range']);
            }
            if (data.hasOwnProperty('shadowed')) {
                obj['shadowed'] = ApiClient.convertToType(data['shadowed'], AnyType);
            }
            if (data.hasOwnProperty('shadower')) {
                obj['shadower'] = ApiClient.convertToType(data['shadower'], AnyType);
            }
            if (data.hasOwnProperty('var')) {
                obj['var'] = ApiClient.convertToType(data['var'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Range} range
 */
ShadowError.prototype['range'] = undefined;

/**
 * @member {module:model/AnyType} shadowed
 */
ShadowError.prototype['shadowed'] = undefined;

/**
 * @member {module:model/AnyType} shadower
 */
ShadowError.prototype['shadower'] = undefined;

/**
 * @member {String} var
 * @default ''
 */
ShadowError.prototype['var'] = '';


// Implement FrontProblem interface:
/**
 * @member {String} type
 * @default ''
 */
FrontProblem.prototype['type'] = '';




export default ShadowError;

