/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractProblem from './AbstractProblem';
import ICViolation from './ICViolation';

/**
 * The IntegrityConstraintViolation model module.
 * @module cloudclient/model/IntegrityConstraintViolation
 * @version 1.0.8
 */
class IntegrityConstraintViolation {
    /**
     * Constructs a new <code>IntegrityConstraintViolation</code>.
     * @alias module:cloudclient/model/IntegrityConstraintViolation
     * @extends module:cloudclient/model/AbstractProblem
     * @implements module:cloudclient/model/AbstractProblem
     * @param type {String} 
     */
    constructor(type) { 
        AbstractProblem.initialize(this, type);
        IntegrityConstraintViolation.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
    }

    /**
     * Constructs a <code>IntegrityConstraintViolation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:cloudclient/model/IntegrityConstraintViolation} obj Optional instance to populate.
     * @return {module:cloudclient/model/IntegrityConstraintViolation} The populated <code>IntegrityConstraintViolation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IntegrityConstraintViolation();
            AbstractProblem.constructFromObject(data, obj);
            AbstractProblem.constructFromObject(data, obj);

            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [ICViolation]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:cloudclient/model/ICViolation>} sources
 */
IntegrityConstraintViolation.prototype['sources'] = undefined;


// Implement AbstractProblem interface:
/**
 * @member {String} type
 * @default ''
 */
AbstractProblem.prototype['type'] = '';




export default IntegrityConstraintViolation;

