/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionResult from './ActionResult';
import Source from './Source';

/**
 * The ListSourceActionResult model module.
 * @module cloudclient/model/ListSourceActionResult
 * @version 1.0.8
 */
class ListSourceActionResult {
    /**
     * Constructs a new <code>ListSourceActionResult</code>.
     * @alias module:cloudclient/model/ListSourceActionResult
     * @extends module:cloudclient/model/ActionResult
     * @implements module:cloudclient/model/ActionResult
     * @param type {String} 
     */
    constructor(type) { 
        ActionResult.initialize(this, type);
        ListSourceActionResult.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
    }

    /**
     * Constructs a <code>ListSourceActionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:cloudclient/model/ListSourceActionResult} obj Optional instance to populate.
     * @return {module:cloudclient/model/ListSourceActionResult} The populated <code>ListSourceActionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListSourceActionResult();
            ActionResult.constructFromObject(data, obj);
            ActionResult.constructFromObject(data, obj);

            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [Source]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:cloudclient/model/Source>} sources
 */
ListSourceActionResult.prototype['sources'] = undefined;


// Implement ActionResult interface:
/**
 * @member {String} type
 * @default ''
 */
ActionResult.prototype['type'] = '';




export default ListSourceActionResult;

