/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DelveClientSdk);
  }
}(this, function(expect, DelveClientSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DelveClientSdk.ClientProblem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClientProblem', function() {
    it('should create an instance of ClientProblem', function() {
      // uncomment below and update the code to test ClientProblem
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be.a(DelveClientSdk.ClientProblem);
    });

    it('should have the property errorCode (base name: "error_code")', function() {
      // uncomment below and update the code to test the property errorCode
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

    it('should have the property isError (base name: "is_error")', function() {
      // uncomment below and update the code to test the property isError
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

    it('should have the property isException (base name: "is_exception")', function() {
      // uncomment below and update the code to test the property isException
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

    it('should have the property report (base name: "report")', function() {
      // uncomment below and update the code to test the property report
      //var instane = new DelveClientSdk.ClientProblem();
      //expect(instance).to.be();
    });

  });

}));
