/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RaiCloudSdk);
  }
}(this, function(expect, RaiCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RaiCloudSdk.ComputeInfoProtocol();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComputeInfoProtocol', function() {
    it('should create an instance of ComputeInfoProtocol', function() {
      // uncomment below and update the code to test ComputeInfoProtocol
      //var instane = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be.a(RaiCloudSdk.ComputeInfoProtocol);
    });

    it('should have the property accountName (base name: "account_name")', function() {
      // uncomment below and update the code to test the property accountName
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property infrastructure (base name: "infrastructure")', function() {
      // uncomment below and update the code to test the property infrastructure
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property requestedOn (base name: "requested_on")', function() {
      // uncomment below and update the code to test the property requestedOn
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "created_on")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property deletedOn (base name: "deleted_on")', function() {
      // uncomment below and update the code to test the property deletedOn
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new RaiCloudSdk.ComputeInfoProtocol();
      //expect(instance).to.be();
    });

  });

}));
